import type { Settings } from "../config/settings.js";

export function testSettings(overrides: Partial<Settings> = {}): Settings {
  return {
    aiProvider: "openrouter",
    openRouterApiKey: "gateway-key",
    openRouterBaseUrl: "http://gateway.example/v1",
    openRouterWebSearchEnabled: true,
    openRouterWebSearchBackend: "ollama",
    openRouterWebSearchMaxResults: 5,
    openRouterWebSearchMaxTotalResults: 15,
    openRouterWebSearchContextSize: "medium",
    cerebrasWebSearchEnabled: false,
    modelStudioWebSearchEnabled: false,
    ollamaApiKeys: ["ollama-key"],
    ollamaSearchHost: "https://ollama.example",
    ollamaWebSearchEnabled: false,
    ollamaWebFetchEnabled: false,
    ollamaWebSearchMaxResults: 3,
    ollamaToolMaxIterations: 4,
    webFetchEnabled: false,
    webFetchTimeoutMs: 1000,
    webFetchMaxBytes: 100000,
    webFetchMaxChars: 12000,
    webFetchMaxTotalChars: 18000,
    chatModel: "gemini-3.7-flash",
    deliveryRewriteEnabled: false,
    chatThinkingMode: "off",
    indexPath: ".planabrain/index.json",
    systemPrompt: "테스트 시스템",
    personaProfile: "live",
    intimacyEnabled: false,
    continuousChat: true,
    searchQueryRewriteEnabled: true,
    memoryEnabled: false,
    memoryMaxMessages: 0,
    memoryDir: ".planabrain/memory",
    ...overrides,
  } as Settings;
}
